---
- hosts: all
  become: true
  tasks:
    - name: Ensure passwordless sudo for ubuntu user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ubuntu'
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

